openapi: 3.1.0
info:
  title: Fédération de collectivités agricoles
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  /collectivities:
    post:
      description: Create a new collectivity
      operationId: newCollectivities
      tags:
        - Collectivity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Collectivity"
      responses:
        '201':
          description: Collectivity created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Collectivity"
        '400':
          description: Collectivity creation not satisfied
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                message: You must complete the informations about the collectivity
                status: 400
        '403':
          description: Collectivity creation not authorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                message: The new Collectivity need to follow all the requirement

  /collectivities/{id}/members:
    post:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 12
      description: Member inscription
      tags:
        - Members
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sponsorId:
                  type: integer
                NewMemberInformations:
                  $ref: "#/components/schemas/Member"
                Transaction:
                  $ref: "#/components/schemas/Transaction"
              example:
                sponsorId: 12
                NewMemberInformations:
                  id: 134
                  name: Rivo Andrianantenaina
                  birthdate: 1988-11-02
                  gender: male
                  address: Lot II M 68 Bis, Ambohimanarina, Antananarivo 101
                  occupation: collector
                  phone: "+261 34 12 345 67"
                  email: rivo.andria@example.mg
                  collectivityId: 3
                Transaction:
                  references: PAR-MDG-20260416-089
                  amount: 50000
                  payment: Orange_money
                  status: success
                  transactionDate: 2026-04-16T09:15:22.123Z
      responses:
        '201':
          description: Welcome to our collectivity
          content:
            application/json:
              schema:
                type: object
                properties:
                  sponsorId:
                    type: integer
                  NewMemberInformations:
                    $ref: "#/components/schemas/Member"
                  Transaction:
                    $ref: "#/components/schemas/Transaction"
              example:
                sponsorId: 12
                NewMemberInformations:
                  id: 134
                  name: Rivo Andrianantenaina
                  birthdate: 1988-11-02
                  gender: male
                  address: Lot II M 68 Bis, Ambohimanarina, Antananarivo 101
                  occupation: collector
                  phone: "+261 34 12 345 67"
                  email: rivo.andria@example.mg
                  collectivityId: 3
                Transaction:
                  references: PAR-MDG-20260416-089
                  amount: 50000
                  payment: Orange_money
                  status: SUCCESS
                  transactionDate: 2026-04-16T09:15:22.123Z
        '400':
          description: Information incomplete
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                message: You must complete all the informations about the new member
                status: 400
        '403':
          description: Admission not authorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                message: Your profile does not meet the requirements for membership
                status: 403

  /members/{id}:
    put:
      description: Change Member informations or collective
      tags:
        - Members
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 17
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Member"
            example:
              id: 17
              name: Miora Faniry Razafimahatratra
              birthdate: 1992-03-18
              gender: female
              address: Lot VA 15 Ter, Andoharanofotsy, Antananarivo 102
              occupation: collector
              phone: "+261 32 98 765 43"
              email: miora.faniry@example.mg
              collectivityId: 3
      responses:
        '200':
          description: Member information updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Member"
              example:
                id: 17
                name: Miora Faniry Razafimahatratra
                birthdate: 1992-03-18
                gender: female
                address: Lot VA 15 Ter, Andoharanofotsy, Antananarivo 102
                occupation: collector
                phone: "+261 32 98 765 43"
                email: miora.faniry@example.mg
                collectivityId: 3
        '404':
          description: Member not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                message: The member from id={id} is not found
                status: 404

    delete:
      tags:
        - Members
      description: Do you want to leave
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 17
      responses:
        '200':
          description: You left
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Member"
              example:
                id: 17
                name: Miora Faniry Razafimahatratra
                birthdate: 1992-03-18
                gender: female
                address: Lot VA 15 Ter, Andoharanofotsy, Antananarivo 102
                occupation: collector
                phone: "+261 32 98 765 43"
                email: miora.faniry@example.mg
        '404':
          description: Member not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                message: The member from id={id} is not found
                status: 404

  /collectivities/{id}/contribution:
    post:
      description: You will Pay your contribution
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      tags:
        - Contribution
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Contribution"
            example:
              memberId: 134
              collectivityId: 4
              period: 2026-04
              contributionPeriod: MONTHLY
              nature: REGULAR
              receiptNumber: REC-20260417-001
              collectedBy: 42
              transaction:
                references: CONT-20260417-089
                amount: 50000
                payment: ORANGE_MONEY
                status: SUCCESS
                transactionDate: 2026-04-17T07:30:34.267Z
      responses:
        '200':
          description: Your contribution is payed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Contribution"
              example:
                memberId: 134
                collectivityId: 4
                period: 2026-04
                contributionPeriod: MONTHLY
                nature: REGULAR
                receiptNumber: REC-20260417-001
                collectedBy: 42
                transaction:
                  references: CONT-20260417-089
                  amount: 50000
                  payment: ORANGE_MONEY
                  status: SUCCESS
                  transactionDate: 2026-04-17T07:30:34.267Z
        '400':
          description: The collectivity from id={id} is not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                message: The collectivity from id={id} is not found
                status: 400

    get:
      description: The note about the contribution
      tags:
        - Contribution
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: This is the note about the contribution from the member number {memberId}
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Contribution"
              example:
                memberId: 134
                collectivityId: 4
                period: 2026-04
                contributionPeriod: MONTHLY
                nature: REGULAR
                receiptNumber: REC-20260417-001
                collectedBy: 42
                transaction:
                  references: CONT-20260417-089
                  amount: 50000
                  payment: ORANGE_MONEY
                  status: SUCCESS
                  transactionDate: 2026-04-17T07:30:34.267Z
                federationShare: 4000
                transferredToFederation: true
        '400':
          description: The collectivity from id={id} is not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                message: The collectivity from id={id} is not found
                status: 400

  /collectivities/{id}/contribution/federation:
    post:
      description: Transfer of the contribution to the federation
      tags:
        - Contribution
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                period:
                  type: string
                transferConfirm:
                  type: boolean
      responses:
        '200':
          description: Transfer succeed
          content:
            application/json:
              schema:
                properties:
                  transferredAmount:
                    type: number
                  contributionCount:
                    type: integer
                  transferDate:
                    type: string
                    format: date-time
                  transaction:
                    $ref: "#/components/schemas/Transaction"
                example:
                  transferredAmount: 10000
                  contributionsCount: 5
                  transferDate: "2026-04-30T23:59:59Z"
                  transaction:
                    references: "FED-TRF-20260430-001"
                    amount: 10000
                    payment: "BANK_TRANSFER"
                    status: "SUCCESS"
                    transactionDate: "2026-04-30T23:59:59Z"

  /collectivities/{id}/accounts:
    post:
      description: add treasury account
      operationId: createCollectivityAccount
      tags: 
        - Account
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        '201':
          description: account created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '404':
          description: Collectivity.id={id} is not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: Collectivity.id=19 is not found
                status: 404

    get:
      description: get account
      tags: 
        - Account
      operationId: getCollectivityAccounts
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: find account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '404':
          description: Collectivity.id={id} is not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: Collectivity.id=19 is not found
                status: 404

  /collectivities/{id}/activities:
    post:
      tags:
        - Activities
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Activity"
            example:
              title: Formation techniques agricoles
              Activitytype: JUNIOR_TRAINING
              date: 2026-04-28
              frequencyDate:
                frequency: MONTHLY
                dayOfWeek: 6
                weekOfMonth: 4
                startDate: 2026-01-01
                endDate: 2026-12-31
              presence: OBLIGATORY
              members: JUNIOR_ONLY
      responses:
        '200':
          description: New activity added
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Activity"
              example:
                title: Assemblée générale mensuelle - Avril 2026
                Activitytype: GENERAL_MEETING
                date: null
                frequencyDate:
                  frequency: MONTHLY
                  dayOfWeek: 4
                  weekOfMonth: 2
                  startDate: 2026-01-01
                  endDate: 2026-12-31
                presence: OBLIGATORY
                members: ALL
        '404':
          description: The collectivity from id={id} is not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                message: The collectivity from id=909 is not found
                status: 404
        '400':
          description: You must complete the informations about the new activity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                message: You must complete the informations about the new activity
                status: 400

    get:
      description: Get activities for a collectivity
      operationId: getCollectivityActivities
      tags:
        - Activities
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of activities
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Activity"
        '404':
          description: Collectivity not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /federation/activities:
    post:
      description: Create an activity for all collectivities
      operationId: createFederationActivity
      tags:
        - Activities
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Activity"
            example:
              title: Assemblée générale mensuelle - Avril 2026
              Activitytype: GENERAL_MEETING
              date: null
              frequencyDate:
                frequency: MONTHLY
                dayOfWeek: 4
                weekOfMonth: 2
                startDate: 2026-01-01
                endDate: 2026-12-31
              presence: OBLIGATORY
              members: ALL
      responses:
        '201':
          description: New activity added
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Activity"
              example:
                title: Assemblée générale mensuelle - Avril 2026
                Activitytype: GENERAL_MEETING
                date: null
                frequencyDate:
                  frequency: MONTHLY
                  dayOfWeek: 4
                  weekOfMonth: 2
                  startDate: 2026-01-01
                  endDate: 2026-12-31
                presence: OBLIGATORY
                members: ALL
        '400':
          description: You must complete the informations about the new activity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                message: You must complete the informations about the new activity
                status: 400

  /activities/{id}/attendance:
    post:
      description: attendance record provided by id
      tags: 
        - Attendances
      operationId: recordAttendance
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Attendance"
      responses:
        '201':
          description: attendance registration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Attendance"
        '404':
          description: activity or member not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: member.id=14 is not found
                status: 404

  /members/{id}/attendance-rate:
    get:
      tags: 
        - Attendances
      description: get attendance rate of a member for a period
      operationId: getAttendanceRate
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: from
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: to
          in: query
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: attendance rate calculated
          content:
            application/json:
              schema:
                type: object
                properties:
                  attendanceRate:
                    type: number
                    format: float
        '400':
          description: missing queryParameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: the parameters 'to' and 'from' are not present
                status: 400
        '404':
          description: member not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: member.id=14 is not found
                status: 404

  /collectivities/{id}/members/stats:
    get:
      tags:
        - Statistics
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: startDate
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          required: true
          schema:
            type: string
            format: date
      description: active members rate
      responses:
        '200':
          description: These are the rate of the active members
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CollectivityStats"
              example:
                globalAttendanceRate: 78.5
                totalMembers: 1240
                activeMembers: 967
        '404':
          description: The collectivity id={id} is not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                message: The collectivity id=111 is not found
                status: 404
        '400':
          description: You must add stats periods
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                message: You must add stats dates
                status: 400

    post:
      tags:
        - Statistics
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CollectivityStatSummary"
            example:
              month: 2025-02-01
              attendanceRate: 79.1
              totalMembers: 1220
      responses:
        '201':
          description: Your report is sent
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CollectivityStatSummary"
              example:
                month: 2025-02-01
                attendanceRate: 79.1
                totalMembers: 1220
        '404':
          description: The collectivity id={id} is not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                message: The collectivity id=167 is not found
                status: 400
        '400':
          description: You must complete your rapport before sending it
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                message: You must complete your rapport before sending it
                status: 400

  /collectivities/{collectivityId}/members/{memberId}/statistics:
    get:
      tags:
        - Statistics
      description: returns a JSON object relating to the detailed statistics by id
      operationId: getMemberStatistics
      parameters:
        - name: collectivityId
          in: path
          required: true
          schema:
            type: integer
        - name: memberId
          in: path
          required: true
          schema:
            type: integer
        - name: from
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: to
          in: query
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Statistics'
        '404':
          description: memberId={memberId} not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Collectivity:
      type: object
      properties:
        id:
          type: integer
        nom:
          type: string
        ville:
          type: string
        speciality:
          type: string
        creationDateTime:
          type: string
          format: date-time

    Member:
      type: object
      required:
        - id
        - name
        - birthdate
        - gender
        - address
        - occupation
        - phone
        - email
        - collectivityId
      properties:
        id:
          type: integer
        name:
          type: string
        birthdate:
          type: string
          format: date
        gender:
          type: string
          enum:
            - male
            - female
        address:
          type: string
        occupation:
          type: string
        phone:
          type: string
        email:
          type: string
          format: email
        collectivityId:
          type: integer

    Positions:
      type: string
      enum:
        - PRESIDENT
        - VICE PRESIDENT
        - TREASURER
        - SECRETARY
        - SENIOR_MEMBER
        - JUNIOR_MEMBER

    Mandate:
      type: object
      required:
        - id
        - collectivityId
        - memberId
        - position
        - startDate
        - endDate
      properties:
        id:
          type: integer
        collectivityId:
          type: integer
        memberId:
          type: integer
        position:
          $ref: "#/components/schemas/Positions"
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date

    Federation:
      type: object
      required:
        - id
        - federationPresident
        - federationVicePresident
        - federationSecretary
        - federationTreasurer
        - mandateStartDate
        - mandateEndDate
      properties:
        id:
          type: integer
        federationPresident:
          $ref: "#/components/schemas/Member"
        federationVicePresident:
          $ref: "#/components/schemas/Member"
        federationSecretary:
          $ref: "#/components/schemas/Member"
        federationTreasurer:
          $ref: "#/components/schemas/Member"
        mandateStartDate:
          type: string
          format: date
        mandateEndDate:
          type: string
          format: date

    Transaction:
      type: object
      required:
        - references
        - amount
        - status
      properties:
        references:
          type: string
        amount:
          type: number
        payment:
          type: string
        status:
          type: string
          enum:
            - SUCCESS
            - FAILURE
        transactionDate:
          type: string
          format: date-time

    Contribution:
      type: object
      properties:
        id:
          type: integer
        memberId:
          type: integer
        collectivityId:
          type: integer
        period:
          type: string
        contributionPeriod:
          type: string
          enum:
            - MONTHLY
            - YEARLY
        nature:
          type: string
          enum:
            - REGULAR
            - SPECIAL_EVENT
            - EMERGENCY
        receiptNumber:
          type: string
        collectedBy:
          type: integer
        transaction:
          $ref: "#/components/schemas/Transaction"
        federationShare:
          type: number
        transferredToFederation:
          type: boolean

    Account:
      type: object
      properties:
        id:
          type: integer
        typeAccount:
          type: string
          enum:
            - BRED
            - MCB
            - BMOI
            - BOA
            - BGFI
            - AFG
            - ACCÈS BANQUE
            - BAOBAB
            - SIPEM
        titulaireName:
          type: string
        accountDetail:
          $ref: '#/components/schemas/AccountDetail'

    AccountDetail:
      type: object
      properties:
        bankCode:
          type: string
          minLength: 5
          maxLength: 5
        boxCode:
          type: string
          minLength: 5
          maxLength: 5
        accountNumber:
          type: string
          minLength: 11
          maxLength: 11
        RIBkey:
          type: string
          minLength: 2
          maxLength: 2

    Activity:
      type: object
      required:
        - title
        - date
        - presence
        - members
      properties:
        title:
          type: string
        Activitytype:
          $ref: "#/components/schemas/ActivityType"
        date:
          description: Date if the activity is one time
          type: string
          format: date
        frequencyDate:
          description: frequency if the activity is recurrent
          allOf:
            - $ref: "#/components/schemas/RecurrenceRules"
        presence:
          type: string
          enum:
            - OBLIGATORY
            - OPTIONAL
        members:
          type: string
          enum:
            - SENIOR_ONLY
            - JUNIOR_ONLY
            - PRESIDENT_ONLY
            - TREASURER_ONLY
            - ALL

    ActivityType:
      type: string
      enum:
        - GENERAL_MEETING
        - JUNIOR_TRAINING
        - EXCEPTIONAL
        - FEDERAL_MEETING

    RecurrenceRules:
      type: object
      required:
        - frequency
        - dayOfWeek
      properties:
        frequency:
          type: string
          enum:
            - MONTHLY
            - YEARLY
        dayOfWeek:
          type: integer
          minimum: 1
          maximum: 7
        weekOfMonth:
          type: integer
          minimum: 1
          maximum: 4
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date

    Attendance:
      type: object
      properties:
        memberId:
          type: integer
        activityId:
          type: integer
        present:
          type: boolean
        justification:
          type: string

    AttendanceRate:
      type: object
      properties:
        attendanceRate:
          type: number
          format: float

    CollectivityStats:
      type: object
      properties:
        globalAttendanceRate:
          type: number
          format: float
        totalMembers:
          type: integer
          description: number of registered members
        activeMembers:
          type: integer
          description: Number of active members

    CollectivityStatSummary:
      type: object
      required:
        - month
        - attendanceRate
        - totalMembers
      properties:
        month:
          type: string
          format: date
        attendanceRate:
          type: number
        totalMembers:
          type: integer

    Statistics:
      type: object
      properties:
        attendanceRate:
          type: number
        totalAmountPaid:
          type: number
          format: float
        unpaidAmount:
          type: number
          format: float

    Error:
      type: object
      properties:
        message:
          type: string
        status:
          type: integer